[package]
name = "streamer"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
devolutions-gateway-task = { path = "../devolutions-gateway-task" }
futures-util = { version = "0.3", features = ["sink"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio = { version = "1.41", features = ["macros"] }
tracing = "0.1"
webm-iterable = { version = "0.6", features = ["futures"] }
