[package]
name = "jmux-proxy"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
description = "JMUX proxy server implementation"
publish = false

[lints]
workspace = true

[dependencies]

# JMUX
jmux-proto = { path = "../jmux-proto" }

# Async
tokio = { version = "1.38", features = ["net", "rt", "io-util", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", features = ["sink"] }

# Error handling
anyhow = "1.0"

# Logging
tracing = "0.1"

# Codec implementation
bytes = "1.6"
bitvec = "1.0"
