[package]
name = "jmux-proxy"
version = "0.0.0"
authors = ["Devolutions Inc."]
edition = "2021"
description = "JMUX proxy server implementation"
publish = false

[dependencies]

# jmux
jmux-proto = { path = "../jmux-proto" }

# async
tokio = { version = "1.17.0", features = ["net", "rt", "io-util", "macros"] }
tokio-util = { version = "0.7.0", features = ["codec"] }
futures-util = { version = "0.3.21", features = ["sink"] }

# error handling
anyhow = "1.0.55"

# logging
slog = "2.7.0"

# codec implementation
bytes = "1.1.0"
bitvec = "1.0.0"

[target.'cfg(loom)'.dependencies]
loom = "0.5.4"
mock-net = { path = "../mock-net" }

[target.'cfg(loom)'.dev-dependencies]
loom = { version = "0.5.4", features = ["futures", "checkpoint"] }

[dev-dependencies]
slog = { version = "2.7.0", features = ["release_max_level_debug"] }
anyhow = "1.0.56"
slog-async = "2.7.0"
slog-term = "2.9.0"
