[package]
name = "rdp-proto"
version = "0.1.0"
authors = ["Vlad Aleksashyn <vlad.al.dp@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
bitflags = "1.0"
num-traits = "0.2"
num-derive = "0.2"
