[package]
name = "job-queue"
version = "0.0.0"
edition = "2021"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
cron_clock = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
time = { version = "0.3", default-features = false }
tracing = "0.1"
uuid = "1.11"


[dev-dependencies]
job-queue-libsql = { version = "0.0.0", path = "../job-queue-libsql" }
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"] }
serde_json = "1.0.140"
tracing-subscriber = { version = "0.3.19", features = ["time"] }
libsql = { version = "0.9", default-features = false, features = [
    "core",
    "serde",
    "replication",
] }
